apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/sweetiu172/nbiot_detector_core.git'
    targetRevision: main
    path: './kubernetes/helm/kibana'
    helm:
      valueFiles:
      - values.extended.yaml
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true